config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "pages#home"

  resources "contacts", only: [:new, :create]
  resources "articles", only: [:index, :show]
  resources "staffs", only: [:index, :show]
  resources "players", only: [:index, :show]

  get "news", to: "pages#news"
  get "eligibility", to: "pages#eligibility"
  get "nationalteam", to: "pages#nationalteam"
  get "contact", to: "pages#contact"
  get "association", to: "pages#association"

end

app/models/ability.rb
class Ability
  include CanCan::Ability

  attr_reader :current_admin_user

  def initialize(admin_user)
  	can :read, :all
    can :manage, Team
    can :manage, Sponsor
    can :manage, Staff
    can :manage, Player
    can :manage, Article
		if admin_user.super_admin == true
  		can :manage, AdminUser
      can :manage, Event
      can :manage, Article
  	else		
	    can :update, AdminUser, :id => admin_user.id 
      can :destroy, AdminUser, :id => admin_user.id 
      can :manage, Event, :admin_user_id => admin_user.id
      can :create, Event
      can :manage, Article, :admin_user_id => admin_user.id
      can :create, Article
	  end
  end

end

app/models/admin_user.rb
class AdminUser < ActiveRecord::Base
  has_many :articles
  has_many :events
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :password, :presence => true,
            :on => [:create, :update],
            :format => {:with => /\A.*(?=.{10,})(?=.*\d)(?=.*[a-z])(?=.*[A-Z])(?=.*[\@\#\$\%\^\&\+\=]).*\Z/, :message => "Password must be at least ten characters, and include a capital letter, lowercase letter, number, and special character"}

  # after_create { |admin| admin.send_reset_password_instructions }

	def password_required?
	 new_record? ? false : super
	end
	
	# new function to set the password without knowing the current 
  # password used in our confirmation controller. 
  def attempt_set_password(params)
    p = {}
    p[:password] = params[:password]
    p[:password_confirmation] = params[:password_confirmation]
    update_attributes(p)
  end

  # new function to return whether a password has been set
  def has_no_password?
    self.encrypted_password.blank?
  end

  # Devise::Models:unless_confirmed` method doesn't exist in Devise 2.0.0 anymore. 
  # Instead you should use `pending_any_confirmation`.  
  def only_if_unconfirmed
    pending_any_confirmation {yield}
  end
  
end

app/models/article.rb
class Article < ActiveRecord::Base
	belongs_to :admin_user

	validates :title, presence: true, length: { minimum: 5, maximum: 100 }
	validates :text, presence: true, length: { minimum: 50 }

	has_attached_file :featured_image, default_url: "/images/noimg.png"
	validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/  
end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Message Sent from lacrosse.hu Contact Form",
      :to => "george@lacrosse.hu",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/event.rb
class Event < ActiveRecord::Base
	belongs_to :admin_user

	validates :admin_user_id, presence: true
	validates :name, presence: true, length: { minimum: 5, maximum: 100 }
	validates :text, presence: true, length: { minimum: 50 }

	has_attached_file :featured_image, default_url: "/images/noimg.png"
	validates_attachment_content_type :featured_image, content_type: /\Aimage\/.*\Z/  
end

app/models/player.rb
class Player < ActiveRecord::Base
	validates :name, presence: true
	validates :number, presence: true
	validates :position, presence: true


	has_attached_file :image, default_url: "/images/noimg.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 
end

app/models/sponsor.rb
class Sponsor < ActiveRecord::Base
	validates :name, presence: true
	validates :priority, presence: true

	has_attached_file :logo, default_url: "/images/noimg.png"
	validates_attachment_content_type :logo, content_type: /\Aimage\/.*\Z/ 
end

app/models/staff.rb
class Staff < ActiveRecord::Base
	validates :name, presence: true
	validates :title, presence: true

	has_attached_file :image, default_url: "/images/noimg.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/ 
end

app/models/team.rb
class Team < ActiveRecord::Base
	validates :name, presence: true

	has_attached_file :image, default_url: "/images/noimg.png"
	validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/  
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable     	
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
	# before_action :authenticate_admin_user!, except: [:index, :show]

	def home
		#Supports News/Article functionality on the home page
		@articles = Article.all.order("published_at DESC").where(:published => true).limit(3)
		@more_articles = true

		#Supports Team functionality on the home page
		@teams = Team.all.order("name ASC")

		#Supports Events functionality on the home page
		@events = Event.all.order("start_date ASC").where(:published => true).limit(2)

		#Supports Events functionality on the home page
		@sponsors = Sponsor.all.order("priority ASC").where(:published => true)
	end

	def nationalteam
		#Supports Staff functionality on the national team page(s)
		@staffs = Staff.all

		#Supports Player functionality on the national team page(s)
		@players = Player.all.order("number ASC")
	end

	def show
		@article = Article.find_by(id: params[:id])
		@staff = Staff.find_by(id: params[:id])
		@player = Player.find_by(id: params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
	def title(page_title)
		content_for(:title) { page_title }
	end

end

app/helpers/article_helper.rb
module ArticleHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/players_helper.rb
module PlayersHelper
end

app/helpers/sponsors_helper.rb
module SponsorsHelper
end

app/helpers/staffs_helper.rb
module StaffsHelper
end

app/helpers/teams_helper.rb
module TeamsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/_edit_user_modal.html.erb
<!-- Button trigger modal -->
<%= link_to 'Account Settings', "#editusermodal", data: {:toggle => "modal", :target => "#editusermodal"} %>

<!-- Modal -->
<div class="modal fade" id="editusermodal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header edit-user-modal-heading">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h1 class="modal-title" id="myModalLabel"><%= image_tag current_user.avatar.url(:thumb), class: "account-avatar" %><span class="center"> Edit <%= resource_name.to_s.humanize %> - <%= current_user.firstname %> <%= current_user.lastname %></span></h1>
      </div>
      <div class="modal-body">
        <%= form_for(resource, as: resource_name, url: registration_path(resource_name), html: { method: :put }) do |f| %>
          <%= devise_error_messages! %>
              
          <div class="form-inline">  <!-- Name Form -->
            <div class="form-group form-group-name" >
              <%= f.label "Last Name" %><br />
              <%= f.text_field :lastname, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>

            <div class="form-group form-group-name">
              <%= f.label "First Name" %><br />
              <%= f.text_field :firstname, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>

            <div class="form-group form-group-mi">
              <%= f.label "MI" %><br />
              <%= f.text_field :mi, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>
          </div>

          <div class="form-inline">  <!-- Contact Info -->
            <div class="form-group form-group-three-line">
              <%= f.label :email %><br />
              <%= f.email_field :email, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>

            <div class="form-group form-group-three-line">
              <%= f.label "Phone Number" %><br />
              <%= f.phone_field :phonenumber, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>  

            <div class="form-group form-group-three-line-end">
              <%= f.label :birthday %><br />
              <%= f.date_field :birthday, autofocus: true, class: "form-control", id: "form-full-width" %>
            </div>

            <% if devise_mapping.confirmable? && resource.pending_reconfirmation? %>
              <div>Currently waiting confirmation for: <%= resource.unconfirmed_email %></div>
            <% end %>
          </div>

          <div class="form-group">  <!-- Avatar -->
              <%= f.label :avatar %><br />
              <%= f.file_field :avatar, class: "form-control" %>
          </div>

          <hr class="form-rule">

          <div class="form-inline">  <!-- Address Form -->
              <div class="form-group form-group-address">
                <%= f.label :address %><br />
                <%= f.text_field :address, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-apt">
                <%= f.label :apt %><br />
                <%= f.text_field :apt, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-three-line">
                <%= f.label :city %><br />
                <%= f.text_field :city, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-three-line">
                <%= f.label :state %><br />
                <%= f.text_field :state, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-three-line-end">
                <%= f.label :zipcode %><br />
                <%= f.number_field :zipcode, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>
          </div>

          <hr class="form-rule">

          <div class="form-inline">  <!-- US Lacrosse Info -->
              <div class="form-group form-group-two-line">
                <%= f.label "US Lacrosse Member Number" %><br />
                <%= f.number_field :uslnumber, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-two-line-end">
                <%= f.label "US Lacrosse Number Expiration Date" %><br />
                <%= f.date_field :uslexpdate, autofocus: true, class: "form-control", id: "form-full-width" %>
              </div>
              <p class="center"><%= link_to "Click here to get one", "https://usl.ebiz.uapps.net/PersonifyEbusiness/Default.aspx?TabID=340&_ga=1.152457785.1872589890.1441135307"%> |
                  <%= link_to "Click here to look it up", "https://usl.ebiz.uapps.net/PersonifyEbusiness/Default.aspx?TabID=266&_ga=1.54883627.1872589890.1441135307" %></p>
          </div>

          <hr class="form-rule">

          <div class="form-inline">  <!-- Password Change -->
              <div class="form-group form-group-two-line">
                <%= f.label :password %> <br />
                <%= f.password_field :password, autocomplete: "off", class: "form-control", id: "form-full-width" %>
              </div>

              <div class="form-group form-group-two-line-end">
                <%= f.label :password_confirmation %><br />
                <%= f.password_field :password_confirmation, autocomplete: "off", class: "form-control", id: "form-full-width"  %>
              </div>
              <i class="center">(leave blank if you don't want to change it)</i>
          </div>

          <div class="form-group">  <!-- Current Password -->
              <%= f.label :current_password %> <i>(we need your current password to confirm your changes)</i><br />
              <%= f.password_field :current_password, autocomplete: "off", class: "form-control" %>
          </div>

          <div class="form-group">
            <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
            <%= f.submit "Update", class: "btn btn-primary" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="container-fluid" id="footer">
	<div class="row">
		<div class="container">
			<div class="col-md-4">
				<!-- <p><%= link_to "Powered by Third Law Studios", "http://www.thirdlawstudios.com" %></p> -->
			</div>
			<div class="col-md-4 center footer">
				<p>&copy; Hungarian Lacrosse Association | 2017</p>
			</div>
			<!-- <div class="col-md-4">
				 <%= link_to image_tag("twitter/TwitterLogo.png", :alt => "Twitter", class: "social-logo"), "https://twitter.com/hungary_lax", {target: "_blank"} %>
			</div> -->
		</div>	
	</div>
</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-fixed-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Hungarian Lacrosse Association", root_path, class: "navbar-brand heavy primary-color" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Home", root_path %></li>
        <!-- <li><%= link_to "Store", "https://www.14graphics.com/hungary-lax", target: "_blank" %></li> -->
        <li><%= link_to "News", root_path(anchor:"news") %></li>
        <li><%= link_to "Teams", root_path(anchor:"teams") %></li>
        <li><%= link_to "Events", root_path(anchor:"events") %></li>
        <li><%= link_to "Sponsors", root_path(anchor:"sponsors") %></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">National Team <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Eligibility Requirements", eligibility_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "Men's National Team", nationalteam_path %></li>
          </ul>
        </li>    
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Association <span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to "Contact", contact_path %></li>
            <li role="separator" class="divider"></li>
            <li><%= link_to "About Us", association_path %></li>
            <li><%= link_to "History", association_path(anchor:"history") %></li>
            <li><%= link_to "Executive Board", association_path(anchor:"board") %></li>
            <li><%= link_to "Media", association_path(anchor:"media") %></li>
            <!-- <li role="separator" class="divider"></li> -->
            <!-- <li><%= link_to "Hungarian Lacrosse Foundation", "http://www.hungarianlacrosse.com", target: "_blank" %></li> -->
          </ul>
        </li>  
        <li>
          <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_blank" style="margin-top:10px;">
            <input type="hidden" name="cmd" value="_s-xclick">
            <input type="hidden" name="hosted_button_id" value="AMBG5GPN2CA9A">
            <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
            <img alt="" border="0" src="https://www.paypalobjects.com/en_US/i/scr/pixel.gif" width="1" height="1">
          </form>
        </li>  
<!--  Removed until login is required
       <% if user_signed_in? %>s
          <li><%= link_to "Account Settings", edit_user_registration_path %></li>
          <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li> 
        <% else %>
          <li><%= link_to "Contact Us", root_path(anchor:"contact") %></li>
          <li><button type="button" class="btn btn-default navbar-btn"><%= link_to "Sign In", new_user_session_path %></li></button>
       <% end %>  -->
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hungarian Lacrosse Association | <%= yield :title || "The Official Site of Lacrosse in Hungary" %></title>
    <%= yield :head_top %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <script src="//load.sumome.com/" data-sumo-site-id="3e1459dc5c28e41f578d4f4deb967329128f80c199a6c43aa3629c379d4ba90b" async="async"></script>
    <%= yield :head_end %>
  </head>
  <body class="parallax">
    <%= yield :body_top %>
    
  	<div>
  		<%= render 'layouts/header' %>
  	</div>
  	
  	<div class="container">
      <% flash.each do |name, msg| %>
        <%= content_tag(:div, msg, class: "row col-lg-8 col-lg-offset-1 alert alert-info first-item", style: "position:fixed;") do %>
          <%= msg %>
          <button type="button" class="close" data-dismiss="alert">&times;</button>
        <% end %>
      <% end %>
    </div>

    <div>
  	  <%= yield %>
    </div>
  		
  	<%= render 'layouts/footer' %>
  	
    <%= yield :body_end %>	
  </body>
</html>

app/views/pages/_welcome_buttons.html.erb
<div>
	<%= link_to "Sign in", new_user_session_path, class: "btn btn-default btn-lg" %> 	
	<%= link_to "Sign up!", new_user_registration_path, class: "btn btn-primary btn-lg" %>
</div>

app/views/pages/association.html.erb
<% title "About Us" %>

<% content_for :head_top do %>
	<meta charset="UTF-8">
	<meta name="description" content="Learn more about the Hungarian Lacrosse Association, our history, and the history of lacrosse in Hungary">
	<meta name="keywords" content="About, History, Lacrosse">
<% end %>
<% content_for :head_end do %>
<% end %>
<% content_for :body_top do %>
<% end %>
<% content_for :body_end do %>
<% end %>

<div class="container" id="association">
	<div class="jumbotron center" id="about">
		<h2 class="section-title">About Us</h2>
		<p>The Hungarian Lacrosse Association is the national governing body for lacrosse in Hungary.  Our goal is to grow and develop lacrosse, in all its forms, in Hungary by providing programs that ensure opportunities exist for individuals to participate and excel in the sport of lacrosse.</p>
	</div>
	<div class="jumbotron" id="history">
		<h2 class="section-title">History</h2>
		<h3>History of Lacrosse</h3>
		<p>Lacrosse may have been developed as early as 1100 AD among indigenous peoples on the North American continent. By the seventeenth century, it was well-established. It was documented by Jesuit missionary priests in the territory of present-day Canada. The game has undergone many modifications since that time.</p>
		<p>In the traditional aboriginal Canadian version, each team consisted of about 100 to 1,000 men on a field that stretched from about 500 m (1,600 ft) to 3 km (1.9 mi) long. These games lasted from sunup to sundown for two to three days straight. These games were played as part of ceremonial ritual, a kind of symbolic warfare, to give thanks to the Creator or Master.</p>
		<p>James Smith described in some detail a game being played in 1757 by his fellow tribe members "wherein now they used a wooden ball, about three inches diameter, and the instrument they moved it with was a strong staff about 5 ft (1.5 m) long, with a hoop net on the end of it, large enough to contain the ball."</p>
		<p>The Italian explorer Count Paolo Andreani documented his contacts with the Oneida people in the 1790s and his reports on the Oneida include an illustration which is thought to be the first recorded picture of a lacrosse stick.</p>
		<p>Lacrosse played a significant role in the community and religious life of tribes across the continent for many years. Early lacrosse was characterized by deep spiritual involvement, befitting the spirit of combat in which it was undertaken. Those who took part did so in the role of warriors, with the goal of bringing glory and honor to themselves and their tribes. The game was said to be played "for the Creator" or was referred to as "The Creator's Game."</p>
		<p>The French Jesuit missionary Jean de Brébeuf saw Iroquois tribesmen play the game during 1637 in present-day New York. He was one of the first Europeans to write about the game. He called it la crosse ("the stick"). The name seems to be originated from the French term for field hockey, le jeu de la crosse. A "crosse" in French is any stick curved at its end (Example: Crosse d'evêque - Bishop's crozier)</p>
		<p>In 1855, William George Beers, a Canadian dentist, founded the Montreal Lacrosse Club. In 1867, Beers codified the game, shortening the length of each game and reducing the number of players to 12 per team. The first game played under Beers' rules was at Upper Canada College in 1867; they lost to the Toronto Cricket Club by a score of 3–1. By the 20th century, teams in high schools, colleges, and universities in Canada and the United States began playing the game.</p>
		<p>Lacrosse was contested for medals in the 1904 and 1908 Olympics with teams from Canada, the United States, and Great Britain. It was contested as a demonstration sport in the 1928 and 1932 Olympics. On each occasion, a playoff was held in the United States to determine what team would go to the Olympics; each time the playoffs were won by Johns Hopkins University in Baltimore, Maryland.</p>
		<p>In the United States, lacrosse during the 1900s was primarily a regional sport centered around the east coast, including the states of Connecticut, New Hampshire, Massachusetts, New York, New Jersey, Pennsylvania, Maryland, Virginia, and North Carolina. However, in the last half of the 20th century, the sport has continued growth west of this region, and in since the beginning of the 21st century in Georgia, Tennessee, Florida, Texas, California, Indiana, and Minnesota. According to a report of a survey conducted by US Lacrosse in 2013, Field Lacrosse is one of the fastest growing sports and the fastest growing team sport in NFHS.
		</p>
		<p>At the highest amateur level, it is represented by the collegiate NCAA Division I in the United States. The first collegiate lacrosse program was established by New York University in 1877. Nearly 100 years later, the 1971 tournament was the first Men's Lacrosse Championship sponsored by the National Collegiate Athletic Association (NCAA).</p>
		<p>In other countries, the sport is also played at a high level on the amateur level by the Australian Lacrosse League, the Canadian University Field Lacrosse Association, and club lacrosse leagues internationally.</p>
		<p>In the summer of 2001, a men's professional field lacrosse league, known as Major League Lacrosse (MLL), was inaugurated in the United States. Initially starting with three teams, the MLL has grown to a current total of nine clubs located in major metropolitan areas in the United States. On July 4, 2008, Major League Lacrosse set the professional lacrosse attendance record: 20,116 fans attended a game at Invesco Field in Denver, Colorado.</p>
		<h3>Lacrosse in Hungary</h3>
		<p>The first appearance of lacrosse in Hungary was at Szombathely in 2002 in the form of an inter-cross team.</p>
		<p>The next step was the broadcasting of the matches of the National Lacrosse League by Eurosport 2 TV network. This gave us the idea to launch lacrosse in Hungary, similarly to other American sports such as baseball and american football.
		The first Hungarian lacrosse club, the Budapest BLAX was founed on March the 16th, 2008.</p>
		<p>Training started in April 2008 under the guidence of Marten Jäger and on May the 3rd Mr Peter J. Mundy, president of the  European Lacrosse Federationand Mr Amit, well-known trainer from London held a clinic in Budapest. Beside teaching the theory, they also taugh training techniques, thus began the sport’s development in Hungary.</p>
		<p>On November the 16th 2008, Hungary had its first international game against the Bratislava Bats.</p>
		<p>In the 2009 season, the Budapest Team played in the Austrian Lacrosse League and finished sixth.</p>
		<p>The womens’ team of Budapest BLAX was formed in March 2010, now playing under the name of Budapest Blackberries.</p>
		<p>In 2011, the Budapest BLAX finished 2nd in the Austrian Lacrosse League, only being defeated by the Vienna Monarchs, who’s roster is almost identicaly to the Austrian National Team’s.</p>
		<p>2015 brought the first international success: Budapest Blax won the first season of the freshly formed Central European Lacrosse League.</p>
</p>
	</div>	
	<div class="jumbotron center" id="board">
		<div class="row">
			<h2 class="section-title">Executive Board</h2>
			<table class="table table-condensed">
				<tr>
					<th>Position</th>
					<th>Name</th>
					<th>E-mail</th>
				</tr>
				<tr>
					<td>President</td>
					<td>George Rohonczy</td>
					<td>george@lacrosse.hu</td>
				</tr>
				<tr>
					<td>Vice-President</td>
					<td>David Urban</td>
					<td>david@lacrosse.hu</td>
				</tr>
				<tr>
					<td>Member</td>
					<td>Brad Jones</td>
					<td>brad@lacrosse.hu</td>
				</tr>
			</table>		
		</div>	
	</div>	
	<div class="jumbotron center" id="media">
		<h2 class="section-title">Media</h2>
	</div>
</div>

app/views/pages/contact.html.erb
<% title "Contact Us" %>

<% content_for :head_top do %>
	<meta charset="UTF-8">
	<meta name="description" content="Want to help? Interested in a sponsorship? This is the easiest way to contact us.">
	<meta name="keywords" content="Contact, Sponsor">
<% end %>
<% content_for :head_end do %>
<% end %>
<% content_for :body_top do %>
<% end %>
<% content_for :body_end do %>
<% end %>

<div class="container">
	<div class="col-xs-12 col-md-8 col-md-offset-2 jumbotron center", id="contact">
		<h2 class="section-title">Contact Us</h2>
		<h3>Want to Join? Interested in a Sponsorship? Drop us a line.</h3>
		<div class="container">
			<div class="row">
				<div class="col-xs-12 col-lg-10 col-lg-offset-1">
					<%= render 'contacts/new' %>
				</div>	
			</div>	
		</div>	
	</div>
</div>

app/views/pages/nationalteam.html.erb
<% title "Men's National Team" %>
<% content_for :head_top do %>
	<meta charset="UTF-8">
	<meta name="description" content="Staff and Roster for the Mens National Team">
	<meta name="keywords" content="National, Team, Hungary, Coaches, Players, Roster">
<% end %>
<% content_for :head_end do %>
<% end %>
<% content_for :body_top do %>
<% end %>
<% content_for :body_end do %>
<% end %>

<div class="container">
	<div class="jumbotron" id="mensnationalteam">
		<h2 class="section-title"><%= yield(:title) %></h2>
		<hr>
		<%= render "/staffs/index.html.erb" %>
		<%= render "/players/index.html.erb" %>
	</div>
</div>	